# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import sesame_hr_python_sdk
from sesame_hr_python_sdk.paths.schedule_v1_holidays_holiday_calendar_id_employees import delete
from sesame_hr_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestScheduleV1HolidaysHolidayCalendarIdEmployees(ApiTestMixin, unittest.TestCase):
    """
    ScheduleV1HolidaysHolidayCalendarIdEmployees unit test stubs
        Unassign Holiday Calendar To Employee
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
