# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from sesame_hr_python_sdk.pydantic.absence_calendars_update_by_id_response_data_absence_type import AbsenceCalendarsUpdateByIdResponseDataAbsenceType
from sesame_hr_python_sdk.pydantic.absence_calendars_update_by_id_response_data_days_off import AbsenceCalendarsUpdateByIdResponseDataDaysOff
from sesame_hr_python_sdk.pydantic.absence_calendars_update_by_id_response_data_employee import AbsenceCalendarsUpdateByIdResponseDataEmployee

class AbsenceCalendarsUpdateByIdResponseData(BaseModel):
    id: typing.Optional[str] = Field(None, alias='id')

    employee: typing.Optional[AbsenceCalendarsUpdateByIdResponseDataEmployee] = Field(None, alias='employee')

    days_off: typing.Optional[AbsenceCalendarsUpdateByIdResponseDataDaysOff] = Field(None, alias='daysOff')

    max_days_off: typing.Optional[int] = Field(None, alias='maxDaysOff')

    year: typing.Optional[int] = Field(None, alias='year')

    absence_type: typing.Optional[AbsenceCalendarsUpdateByIdResponseDataAbsenceType] = Field(None, alias='absenceType')

    created_at: typing.Optional[str] = Field(None, alias='createdAt')

    updated_at: typing.Optional[str] = Field(None, alias='updatedAt')

    deleted_at: typing.Optional[typing.Optional[str]] = Field(None, alias='deletedAt')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
