# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class AgreementsListResponseDataItem(BaseModel):
    id: typing.Optional[str] = Field(None, alias='id')

    company_id: typing.Optional[str] = Field(None, alias='companyId')

    name: typing.Optional[str] = Field(None, alias='name')

    code: typing.Optional[str] = Field(None, alias='code')

    color: typing.Optional[str] = Field(None, alias='color')

    annual_hours: typing.Optional[typing.Union[int, float]] = Field(None, alias='annualHours')

    additional_hours_percent: typing.Optional[typing.Union[int, float]] = Field(None, alias='additionalHoursPercent')

    total_additional_hours: typing.Optional[typing.Union[int, float]] = Field(None, alias='totalAdditionalHours')

    max_days_to_work: typing.Optional[typing.Union[int, float]] = Field(None, alias='maxDaysToWork')

    created_at: typing.Optional[str] = Field(None, alias='createdAt')

    updated_at: typing.Optional[str] = Field(None, alias='updatedAt')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
