# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from sesame_hr_python_sdk.pydantic.check_validation_list_by_employees_and_status_response_data_item_employee import CheckValidationListByEmployeesAndStatusResponseDataItemEmployee

class CheckValidationListByEmployeesAndStatusResponseDataItem(BaseModel):
    id: typing.Optional[str] = Field(None, alias='id')

    employee: typing.Optional[CheckValidationListByEmployeesAndStatusResponseDataItemEmployee] = Field(None, alias='employee')

    start_date: typing.Optional[str] = Field(None, alias='startDate')

    end_date: typing.Optional[str] = Field(None, alias='endDate')

    status: typing.Optional[str] = Field(None, alias='status')

    last_sent: typing.Optional[typing.Optional[str]] = Field(None, alias='lastSent')

    times_sent: typing.Optional[int] = Field(None, alias='timesSent')

    created_at: typing.Optional[str] = Field(None, alias='createdAt')

    updated_at: typing.Optional[str] = Field(None, alias='updatedAt')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
