# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from sesame_hr_python_sdk.pydantic.contracts_get_current_contract_by_employee_id_response_data_contract_type import ContractsGetCurrentContractByEmployeeIdResponseDataContractType
from sesame_hr_python_sdk.pydantic.contracts_get_current_contract_by_employee_id_response_data_degree import ContractsGetCurrentContractByEmployeeIdResponseDataDegree
from sesame_hr_python_sdk.pydantic.contracts_get_current_contract_by_employee_id_response_data_holidays import ContractsGetCurrentContractByEmployeeIdResponseDataHolidays
from sesame_hr_python_sdk.pydantic.contracts_get_current_contract_by_employee_id_response_data_job_charge import ContractsGetCurrentContractByEmployeeIdResponseDataJobCharge
from sesame_hr_python_sdk.pydantic.contracts_get_current_contract_by_employee_id_response_data_trial_period import ContractsGetCurrentContractByEmployeeIdResponseDataTrialPeriod
from sesame_hr_python_sdk.pydantic.contracts_get_current_contract_by_employee_id_response_data_workday_type import ContractsGetCurrentContractByEmployeeIdResponseDataWorkdayType

class ContractsGetCurrentContractByEmployeeIdResponseData(BaseModel):
    id: typing.Optional[str] = Field(None, alias='id')

    status: typing.Optional[str] = Field(None, alias='status')

    job_charge: typing.Optional[ContractsGetCurrentContractByEmployeeIdResponseDataJobCharge] = Field(None, alias='jobCharge')

    workday_type: typing.Optional[ContractsGetCurrentContractByEmployeeIdResponseDataWorkdayType] = Field(None, alias='workdayType')

    contract_type: typing.Optional[ContractsGetCurrentContractByEmployeeIdResponseDataContractType] = Field(None, alias='contractType')

    degree: typing.Optional[ContractsGetCurrentContractByEmployeeIdResponseDataDegree] = Field(None, alias='degree')

    agreement: typing.Optional[str] = Field(None, alias='agreement')

    start_at: typing.Optional[str] = Field(None, alias='startAt')

    end_at: typing.Optional[str] = Field(None, alias='endAt')

    comment: typing.Optional[str] = Field(None, alias='comment')

    trial_period: typing.Optional[ContractsGetCurrentContractByEmployeeIdResponseDataTrialPeriod] = Field(None, alias='trialPeriod')

    code: typing.Optional[str] = Field(None, alias='code')

    social_security_number: typing.Optional[str] = Field(None, alias='socialSecurityNumber')

    holidays: typing.Optional[ContractsGetCurrentContractByEmployeeIdResponseDataHolidays] = Field(None, alias='holidays')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
