# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ContractsGetCurrentContractByEmployeeIdResponseDataTrialPeriod(BaseModel):
    quantity: typing.Optional[int] = Field(None, alias='quantity')

    trial_period_type: typing.Optional[str] = Field(None, alias='trialPeriodType')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
