# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class ContractsUpdateContractRequest(BaseModel):
    # Start date of contract
    start_at: date = Field(alias='startAt')

    # Code of the contract
    code: str = Field(alias='code')

    # end date of contract
    end_at: typing.Optional[date] = Field(None, alias='endAt')

    # Comments
    comment: typing.Optional[str] = Field(None, alias='comment')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
