# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from sesame_hr_python_sdk.pydantic.employee_schedule_templates_list_templates_response_data_item20240101 import EmployeeScheduleTemplatesListTemplatesResponseDataItem20240101

class EmployeeScheduleTemplatesListTemplatesResponseDataItem(BaseModel):
    2024-01-01_: typing.Optional[EmployeeScheduleTemplatesListTemplatesResponseDataItem20240101] = Field(None, alias='2024-01-01')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
