# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class EmployeeAgreementsAssignEmployeeRequest(BaseModel):
    # Agreement UUID
    agreement_id: str = Field(alias='agreementId')

    # Employee UUID
    employee_id: str = Field(alias='employeeId')

    # Start date
    start_date: date = Field(alias='startDate')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
