# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from sesame_hr_python_sdk.pydantic.employee_managers_assign_response_data_employee import EmployeeManagersAssignResponseDataEmployee
from sesame_hr_python_sdk.pydantic.employee_managers_assign_response_data_manager import EmployeeManagersAssignResponseDataManager

class EmployeeManagersAssignResponseData(BaseModel):
    id: typing.Optional[str] = Field(None, alias='id')

    manager: typing.Optional[EmployeeManagersAssignResponseDataManager] = Field(None, alias='manager')

    employee: typing.Optional[EmployeeManagersAssignResponseDataEmployee] = Field(None, alias='employee')

    permission: typing.Optional[Literal["check", "vacation"]] = Field(None, alias='permission')

    order: typing.Optional[Literal[0, 1]] = Field(None, alias='order')

    created_at: typing.Optional[str] = Field(None, alias='createdAt')

    updated_at: typing.Optional[str] = Field(None, alias='updatedAt')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
