# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from sesame_hr_python_sdk.pydantic.holidays_unassign_holiday_calendar_to_employee_request_employees import HolidaysUnassignHolidayCalendarToEmployeeRequestEmployees

class HolidaysUnassignHolidayCalendarToEmployeeRequest(BaseModel):
    employees: typing.Optional[HolidaysUnassignHolidayCalendarToEmployeeRequestEmployees] = Field(None, alias='employees')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
