# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from sesame_hr_python_sdk.pydantic.offices_update_by_id_response_data_coordinates import OfficesUpdateByIdResponseDataCoordinates

class OfficesUpdateByIdResponseData(BaseModel):
    description: typing.Optional[str] = Field(None, alias='description')

    id: typing.Optional[str] = Field(None, alias='id')

    name: typing.Optional[str] = Field(None, alias='name')

    address: typing.Optional[str] = Field(None, alias='address')

    coordinates: typing.Optional[OfficesUpdateByIdResponseDataCoordinates] = Field(None, alias='coordinates')

    radio: typing.Optional[int] = Field(None, alias='radio')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
