# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from sesame_hr_python_sdk.pydantic.projects_create_project_response_data_customer import ProjectsCreateProjectResponseDataCustomer
from sesame_hr_python_sdk.pydantic.projects_create_project_response_data_manager import ProjectsCreateProjectResponseDataManager
from sesame_hr_python_sdk.pydantic.projects_create_project_response_data_parent_project import ProjectsCreateProjectResponseDataParentProject

class ProjectsCreateProjectResponseData(BaseModel):
    description: typing.Optional[str] = Field(None, alias='description')

    id: typing.Optional[str] = Field(None, alias='id')

    name: typing.Optional[str] = Field(None, alias='name')

    parent_project: typing.Optional[ProjectsCreateProjectResponseDataParentProject] = Field(None, alias='parentProject')

    customer: typing.Optional[ProjectsCreateProjectResponseDataCustomer] = Field(None, alias='customer')

    price: typing.Optional[typing.Union[int, float]] = Field(None, alias='price')

    start_date: typing.Optional[date] = Field(None, alias='startDate')

    end_date: typing.Optional[date] = Field(None, alias='endDate')

    manager: typing.Optional[ProjectsCreateProjectResponseDataManager] = Field(None, alias='manager')

    status: typing.Optional[Literal["active", "inactive", "paused"]] = Field(None, alias='status')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
