# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from sesame_hr_python_sdk.pydantic.time_entries_start_entry_request_tag_ids import TimeEntriesStartEntryRequestTagIds

class TimeEntriesStartEntryRequest(BaseModel):
    employee_id: str = Field(alias='employeeId')

    project_id: typing.Optional[str] = Field(None, alias='projectId')

    tag_ids: typing.Optional[TimeEntriesStartEntryRequestTagIds] = Field(None, alias='tagIds')

    comment: typing.Optional[str] = Field(None, alias='comment')

    coordinates: typing.Optional[typing.Union[bool, date, datetime, dict, float, int, list, str, None]] = Field(None, alias='coordinates')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
