# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from sesame_hr_python_sdk.pydantic.vacation_calendars_create_new_calendar_request_days_off import VacationCalendarsCreateNewCalendarRequestDaysOff

class VacationCalendarsCreateNewCalendarRequest(BaseModel):
    employee_id: str = Field(alias='employeeId')

    vacation_configuration_id: str = Field(alias='vacationConfigurationId')

    year: int = Field(alias='year')

    days_off: VacationCalendarsCreateNewCalendarRequestDaysOff = Field(alias='daysOff')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
