# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sesame_hr_python_sdk
from sesame_hr_python_sdk.model.vacation_calendars_update_calendar_response_data_vacation_configuration import VacationCalendarsUpdateCalendarResponseDataVacationConfiguration
from sesame_hr_python_sdk import configuration


class TestVacationCalendarsUpdateCalendarResponseDataVacationConfiguration(unittest.TestCase):
    """VacationCalendarsUpdateCalendarResponseDataVacationConfiguration unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
