# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sesame_hr_python_sdk
from sesame_hr_python_sdk.model.vacation_calendars_list_calendars_response_data_item_vacation_configuration import VacationCalendarsListCalendarsResponseDataItemVacationConfiguration
from sesame_hr_python_sdk import configuration


class TestVacationCalendarsListCalendarsResponseDataItemVacationConfiguration(unittest.TestCase):
    """VacationCalendarsListCalendarsResponseDataItemVacationConfiguration unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
