# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sesame_hr_python_sdk
from sesame_hr_python_sdk.model.vacation_day_off_requests_delete_by_id_response import VacationDayOffRequestsDeleteByIdResponse
from sesame_hr_python_sdk import configuration


class TestVacationDayOffRequestsDeleteByIdResponse(unittest.TestCase):
    """VacationDayOffRequestsDeleteByIdResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
