# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sesame_hr_python_sdk
from sesame_hr_python_sdk.model.employee_office_assignations_list_assignations_response_data_item_employee_custom_fields_item import EmployeeOfficeAssignationsListAssignationsResponseDataItemEmployeeCustomFieldsItem
from sesame_hr_python_sdk import configuration


class TestEmployeeOfficeAssignationsListAssignationsResponseDataItemEmployeeCustomFieldsItem(unittest.TestCase):
    """EmployeeOfficeAssignationsListAssignationsResponseDataItemEmployeeCustomFieldsItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
