# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sesame_hr_python_sdk
from sesame_hr_python_sdk.model.work_entries_update_work_entry_response_data_employee import WorkEntriesUpdateWorkEntryResponseDataEmployee
from sesame_hr_python_sdk import configuration


class TestWorkEntriesUpdateWorkEntryResponseDataEmployee(unittest.TestCase):
    """WorkEntriesUpdateWorkEntryResponseDataEmployee unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
