# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sesame_hr_python_sdk
from sesame_hr_python_sdk.model.check_validation_list_by_employees_and_status_response_data_item import CheckValidationListByEmployeesAndStatusResponseDataItem
from sesame_hr_python_sdk import configuration


class TestCheckValidationListByEmployeesAndStatusResponseDataItem(unittest.TestCase):
    """CheckValidationListByEmployeesAndStatusResponseDataItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
