# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import sesame_hr_python_sdk
from sesame_hr_python_sdk.model.salaries_delete_salary_response_meta import SalariesDeleteSalaryResponseMeta
from sesame_hr_python_sdk import configuration


class TestSalariesDeleteSalaryResponseMeta(unittest.TestCase):
    """SalariesDeleteSalaryResponseMeta unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
