# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.absence_day_off_requests_create_day_off_request_response_data_absence_calendar_absence_type_company import AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceTypeCompany

class RequiredAbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceType(TypedDict):
    pass

class OptionalAbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceType(TypedDict, total=False):
    id: str

    name: str

    needsValidation: bool

    company: AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceTypeCompany

    createdAt: str

    updatedAt: str

    deletedAt: typing.Optional[str]

    type: str

    pickMode: str

class AbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceType(RequiredAbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceType, OptionalAbsenceDayOffRequestsCreateDayOffRequestResponseDataAbsenceCalendarAbsenceType):
    pass
