# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.absence_day_off_requests_accept_request_response_data_absence_calendar import AbsenceDayOffRequestsAcceptRequestResponseDataAbsenceCalendar
from sesame_hr_python_sdk.type.absence_day_off_requests_accept_request_response_data_days_off import AbsenceDayOffRequestsAcceptRequestResponseDataDaysOff
from sesame_hr_python_sdk.type.absence_day_off_requests_accept_request_response_data_employee import AbsenceDayOffRequestsAcceptRequestResponseDataEmployee

class RequiredAbsenceDayOffRequestsAcceptRequestResponseData(TypedDict):
    pass

class OptionalAbsenceDayOffRequestsAcceptRequestResponseData(TypedDict, total=False):
    id: str

    absenceCalendar: AbsenceDayOffRequestsAcceptRequestResponseDataAbsenceCalendar

    employee: AbsenceDayOffRequestsAcceptRequestResponseDataEmployee

    daysOff: AbsenceDayOffRequestsAcceptRequestResponseDataDaysOff

    status: str

    type: str

    comment: str

    resolutionComment: str

    resolvedAt: str

    createdAt: str

    updatedAt: str

    deletedAt: str

class AbsenceDayOffRequestsAcceptRequestResponseData(RequiredAbsenceDayOffRequestsAcceptRequestResponseData, OptionalAbsenceDayOffRequestsAcceptRequestResponseData):
    pass
