# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.absence_types_list_response_data_item_company import AbsenceTypesListResponseDataItemCompany

class RequiredAbsenceTypesListResponseDataItem(TypedDict):
    pass

class OptionalAbsenceTypesListResponseDataItem(TypedDict, total=False):
    id: str

    name: str

    needsValidation: bool

    company: AbsenceTypesListResponseDataItemCompany

    createdAt: str

    updatedAt: str

    deletedAt: typing.Optional[str]

    type: str

    pickMode: str

class AbsenceTypesListResponseDataItem(RequiredAbsenceTypesListResponseDataItem, OptionalAbsenceTypesListResponseDataItem):
    pass
