# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.check_types_list_types_response_data import CheckTypesListTypesResponseData
from sesame_hr_python_sdk.type.check_types_list_types_response_meta import CheckTypesListTypesResponseMeta

class RequiredCheckTypesListTypesResponse(TypedDict):
    pass

class OptionalCheckTypesListTypesResponse(TypedDict, total=False):
    data: CheckTypesListTypesResponseData

    meta: CheckTypesListTypesResponseMeta

class CheckTypesListTypesResponse(RequiredCheckTypesListTypesResponse, OptionalCheckTypesListTypesResponse):
    pass
