# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.check_validation_list_by_employees_and_status_response_data_item_employee import CheckValidationListByEmployeesAndStatusResponseDataItemEmployee

class RequiredCheckValidationListByEmployeesAndStatusResponseDataItem(TypedDict):
    pass

class OptionalCheckValidationListByEmployeesAndStatusResponseDataItem(TypedDict, total=False):
    id: str

    employee: CheckValidationListByEmployeesAndStatusResponseDataItemEmployee

    startDate: str

    endDate: str

    status: str

    lastSent: typing.Optional[str]

    timesSent: int

    createdAt: str

    updatedAt: str

class CheckValidationListByEmployeesAndStatusResponseDataItem(RequiredCheckValidationListByEmployeesAndStatusResponseDataItem, OptionalCheckValidationListByEmployeesAndStatusResponseDataItem):
    pass
