# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredContractsUpdateContractRequest(TypedDict):
    # Start date of contract
    startAt: date

    # Code of the contract
    code: str

class OptionalContractsUpdateContractRequest(TypedDict, total=False):
    # end date of contract
    endAt: date

    # Comments
    comment: str

class ContractsUpdateContractRequest(RequiredContractsUpdateContractRequest, OptionalContractsUpdateContractRequest):
    pass
