# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.contracts_create_new_contract_response_data import ContractsCreateNewContractResponseData
from sesame_hr_python_sdk.type.contracts_create_new_contract_response_meta import ContractsCreateNewContractResponseMeta

class RequiredContractsCreateNewContractResponse(TypedDict):
    pass

class OptionalContractsCreateNewContractResponse(TypedDict, total=False):
    data: ContractsCreateNewContractResponseData

    meta: ContractsCreateNewContractResponseMeta

class ContractsCreateNewContractResponse(RequiredContractsCreateNewContractResponse, OptionalContractsCreateNewContractResponse):
    pass
