# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.contracts_get_by_employee_id_response_data import ContractsGetByEmployeeIdResponseData
from sesame_hr_python_sdk.type.contracts_get_by_employee_id_response_meta import ContractsGetByEmployeeIdResponseMeta

class RequiredContractsGetByEmployeeIdResponse(TypedDict):
    pass

class OptionalContractsGetByEmployeeIdResponse(TypedDict, total=False):
    data: ContractsGetByEmployeeIdResponseData

    meta: ContractsGetByEmployeeIdResponseMeta

class ContractsGetByEmployeeIdResponse(RequiredContractsGetByEmployeeIdResponse, OptionalContractsGetByEmployeeIdResponse):
    pass
