# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.contracts_get_current_contract_by_employee_id_response_data_contract_type import ContractsGetCurrentContractByEmployeeIdResponseDataContractType
from sesame_hr_python_sdk.type.contracts_get_current_contract_by_employee_id_response_data_degree import ContractsGetCurrentContractByEmployeeIdResponseDataDegree
from sesame_hr_python_sdk.type.contracts_get_current_contract_by_employee_id_response_data_holidays import ContractsGetCurrentContractByEmployeeIdResponseDataHolidays
from sesame_hr_python_sdk.type.contracts_get_current_contract_by_employee_id_response_data_job_charge import ContractsGetCurrentContractByEmployeeIdResponseDataJobCharge
from sesame_hr_python_sdk.type.contracts_get_current_contract_by_employee_id_response_data_trial_period import ContractsGetCurrentContractByEmployeeIdResponseDataTrialPeriod
from sesame_hr_python_sdk.type.contracts_get_current_contract_by_employee_id_response_data_workday_type import ContractsGetCurrentContractByEmployeeIdResponseDataWorkdayType

class RequiredContractsGetCurrentContractByEmployeeIdResponseData(TypedDict):
    pass

class OptionalContractsGetCurrentContractByEmployeeIdResponseData(TypedDict, total=False):
    id: str

    status: str

    jobCharge: ContractsGetCurrentContractByEmployeeIdResponseDataJobCharge

    workdayType: ContractsGetCurrentContractByEmployeeIdResponseDataWorkdayType

    contractType: ContractsGetCurrentContractByEmployeeIdResponseDataContractType

    degree: ContractsGetCurrentContractByEmployeeIdResponseDataDegree

    agreement: str

    startAt: str

    endAt: str

    comment: str

    trialPeriod: ContractsGetCurrentContractByEmployeeIdResponseDataTrialPeriod

    code: str

    socialSecurityNumber: str

    holidays: ContractsGetCurrentContractByEmployeeIdResponseDataHolidays

class ContractsGetCurrentContractByEmployeeIdResponseData(RequiredContractsGetCurrentContractByEmployeeIdResponseData, OptionalContractsGetCurrentContractByEmployeeIdResponseData):
    pass
