# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.core_v3_employee_custom_fields_item import CoreV3EmployeeCustomFieldsItem

CoreV3EmployeeCustomFields = typing.List[CoreV3EmployeeCustomFieldsItem]
