# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.customers_list_response_data import CustomersListResponseData
from sesame_hr_python_sdk.type.customers_list_response_meta import CustomersListResponseMeta

class RequiredCustomersListResponse(TypedDict):
    pass

class OptionalCustomersListResponse(TypedDict, total=False):
    data: CustomersListResponseData

    meta: CustomersListResponseMeta

class CustomersListResponse(RequiredCustomersListResponse, OptionalCustomersListResponse):
    pass
