# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.departments_create_new_department_response_data import DepartmentsCreateNewDepartmentResponseData
from sesame_hr_python_sdk.type.departments_create_new_department_response_meta import DepartmentsCreateNewDepartmentResponseMeta

class RequiredDepartmentsCreateNewDepartmentResponse(TypedDict):
    pass

class OptionalDepartmentsCreateNewDepartmentResponse(TypedDict, total=False):
    data: DepartmentsCreateNewDepartmentResponseData

    meta: DepartmentsCreateNewDepartmentResponseMeta

class DepartmentsCreateNewDepartmentResponse(RequiredDepartmentsCreateNewDepartmentResponse, OptionalDepartmentsCreateNewDepartmentResponse):
    pass
