# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.documents_list_directories_response_data import DocumentsListDirectoriesResponseData
from sesame_hr_python_sdk.type.documents_list_directories_response_meta import DocumentsListDirectoriesResponseMeta

class RequiredDocumentsListDirectoriesResponse(TypedDict):
    pass

class OptionalDocumentsListDirectoriesResponse(TypedDict, total=False):
    data: DocumentsListDirectoriesResponseData

    meta: DocumentsListDirectoriesResponseMeta

class DocumentsListDirectoriesResponse(RequiredDocumentsListDirectoriesResponse, OptionalDocumentsListDirectoriesResponse):
    pass
