# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDocumentsUploadNewDocumentRequest(TypedDict):
    # Document to upload
    document: typing.IO

class OptionalDocumentsUploadNewDocumentRequest(TypedDict, total=False):
    # Original date of document (Required for payrolls)
    originalDate: date

    # Name for the document
    name: str

class DocumentsUploadNewDocumentRequest(RequiredDocumentsUploadNewDocumentRequest, OptionalDocumentsUploadNewDocumentRequest):
    pass
