# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.employee_assignations_roles_assign_role_response_meta import EmployeeAssignationsRolesAssignRoleResponseMeta

class RequiredEmployeeAssignationsRolesAssignRoleResponse(TypedDict):
    pass

class OptionalEmployeeAssignationsRolesAssignRoleResponse(TypedDict, total=False):
    data: str

    meta: EmployeeAssignationsRolesAssignRoleResponseMeta

class EmployeeAssignationsRolesAssignRoleResponse(RequiredEmployeeAssignationsRolesAssignRoleResponse, OptionalEmployeeAssignationsRolesAssignRoleResponse):
    pass
