# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.employee_schedule_templates_list_templates_response_data_item20240101_item_weekdays_ranges import EmployeeScheduleTemplatesListTemplatesResponseDataItem20240101ItemWeekdaysRanges

class RequiredEmployeeScheduleTemplatesListTemplatesResponseDataItem20240101Item(TypedDict):
    pass

class OptionalEmployeeScheduleTemplatesListTemplatesResponseDataItem20240101Item(TypedDict, total=False):
    id: str

    name: str

    mondayMinutes: int

    tuesdayMinutes: int

    wednesdayMinutes: int

    thursdayMinutes: int

    fridayMinutes: int

    saturdayMinutes: int

    sundayMinutes: int

    currentDayMinutes: int

    weekdaysRanges: EmployeeScheduleTemplatesListTemplatesResponseDataItem20240101ItemWeekdaysRanges

class EmployeeScheduleTemplatesListTemplatesResponseDataItem20240101Item(RequiredEmployeeScheduleTemplatesListTemplatesResponseDataItem20240101Item, OptionalEmployeeScheduleTemplatesListTemplatesResponseDataItem20240101Item):
    pass
