# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.employee_office_assignations_assign_employee_to_office_response_data_office_coordinates import EmployeeOfficeAssignationsAssignEmployeeToOfficeResponseDataOfficeCoordinates

class RequiredEmployeeOfficeAssignationsAssignEmployeeToOfficeResponseDataOffice(TypedDict):
    pass

class OptionalEmployeeOfficeAssignationsAssignEmployeeToOfficeResponseDataOffice(TypedDict, total=False):
    description: str

    id: str

    name: str

    address: str

    coordinates: EmployeeOfficeAssignationsAssignEmployeeToOfficeResponseDataOfficeCoordinates

    radio: int

class EmployeeOfficeAssignationsAssignEmployeeToOfficeResponseDataOffice(RequiredEmployeeOfficeAssignationsAssignEmployeeToOfficeResponseDataOffice, OptionalEmployeeOfficeAssignationsAssignEmployeeToOfficeResponseDataOffice):
    pass
