# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.employees_update_by_id_response_data import EmployeesUpdateByIdResponseData
from sesame_hr_python_sdk.type.employees_update_by_id_response_meta import EmployeesUpdateByIdResponseMeta

class RequiredEmployeesUpdateByIdResponse(TypedDict):
    pass

class OptionalEmployeesUpdateByIdResponse(TypedDict, total=False):
    data: EmployeesUpdateByIdResponseData

    meta: EmployeesUpdateByIdResponseMeta

class EmployeesUpdateByIdResponse(RequiredEmployeesUpdateByIdResponse, OptionalEmployeesUpdateByIdResponse):
    pass
