# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.employee_assignations_roles_list_by_employee_response_data import EmployeeAssignationsRolesListByEmployeeResponseData
from sesame_hr_python_sdk.type.employee_assignations_roles_list_by_employee_response_meta import EmployeeAssignationsRolesListByEmployeeResponseMeta

class RequiredEmployeeAssignationsRolesListByEmployeeResponse(TypedDict):
    pass

class OptionalEmployeeAssignationsRolesListByEmployeeResponse(TypedDict, total=False):
    data: EmployeeAssignationsRolesListByEmployeeResponseData

    meta: EmployeeAssignationsRolesListByEmployeeResponseMeta

class EmployeeAssignationsRolesListByEmployeeResponse(RequiredEmployeeAssignationsRolesListByEmployeeResponse, OptionalEmployeeAssignationsRolesListByEmployeeResponse):
    pass
