# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.holidays_assign_to_employee_request_employees import HolidaysAssignToEmployeeRequestEmployees

class RequiredHolidaysAssignToEmployeeRequest(TypedDict):
    pass

class OptionalHolidaysAssignToEmployeeRequest(TypedDict, total=False):
    employees: HolidaysAssignToEmployeeRequestEmployees

    startDate: date

class HolidaysAssignToEmployeeRequest(RequiredHolidaysAssignToEmployeeRequest, OptionalHolidaysAssignToEmployeeRequest):
    pass
