# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.holiday_calendars_list_calendar_response_data_item_day_off_item import HolidayCalendarsListCalendarResponseDataItemDayOffItem

HolidayCalendarsListCalendarResponseDataItemDayOff = typing.List[HolidayCalendarsListCalendarResponseDataItemDayOffItem]
