# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.projects_list_response_data_item_customer import ProjectsListResponseDataItemCustomer
from sesame_hr_python_sdk.type.projects_list_response_data_item_manager import ProjectsListResponseDataItemManager
from sesame_hr_python_sdk.type.projects_list_response_data_item_parent_project import ProjectsListResponseDataItemParentProject

class RequiredProjectsListResponseDataItem(TypedDict):
    pass

class OptionalProjectsListResponseDataItem(TypedDict, total=False):
    description: str

    id: str

    name: str

    parentProject: typing.Optional[ProjectsListResponseDataItemParentProject]

    customer: ProjectsListResponseDataItemCustomer

    price: typing.Union[int, float]

    startDate: date

    endDate: date

    manager: ProjectsListResponseDataItemManager

    status: str

class ProjectsListResponseDataItem(RequiredProjectsListResponseDataItem, OptionalProjectsListResponseDataItem):
    pass
