# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredRecruitmentCreateCandidateRequest(TypedDict):
    # The first name of the candidate
    firstName: str

    # The last name of the candidate
    lastName: str

    email: str

    # The phone number of the candidate
    phone: str

    # The identifier of the vacancy where the candidate will be added
    vacancyId: str

class OptionalRecruitmentCreateCandidateRequest(TypedDict, total=False):
    # The LinkedIn URL of the candidate
    linkedinURL: str

    # The desired salary of the candidate
    desiredSalary: str

    # The start work date of the candidate
    startWorkDate: str

    # The web of the candidate
    web: str

    # The location of the candidate
    location: str

    # The identifier of the status of the candidate
    statusId: str

class RecruitmentCreateCandidateRequest(RequiredRecruitmentCreateCandidateRequest, OptionalRecruitmentCreateCandidateRequest):
    pass
