# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.recruitment_create_candidate_response_data_vacancy_category import RecruitmentCreateCandidateResponseDataVacancyCategory
from sesame_hr_python_sdk.type.recruitment_create_candidate_response_data_vacancy_location_vacancy import RecruitmentCreateCandidateResponseDataVacancyLocationVacancy
from sesame_hr_python_sdk.type.recruitment_create_candidate_response_data_vacancy_schedule_type import RecruitmentCreateCandidateResponseDataVacancyScheduleType

class RequiredRecruitmentCreateCandidateResponseDataVacancy(TypedDict):
    pass

class OptionalRecruitmentCreateCandidateResponseDataVacancy(TypedDict, total=False):
    description: str

    id: str

    companyId: str

    name: str

    department: str

    contactType: str

    experience: str

    createdById: str

    status: str

    openedAt: str

    createdAt: str

    updatedAt: str

    public: bool

    locationVacancy: RecruitmentCreateCandidateResponseDataVacancyLocationVacancy

    scheduleType: RecruitmentCreateCandidateResponseDataVacancyScheduleType

    category: RecruitmentCreateCandidateResponseDataVacancyCategory

class RecruitmentCreateCandidateResponseDataVacancy(RequiredRecruitmentCreateCandidateResponseDataVacancy, OptionalRecruitmentCreateCandidateResponseDataVacancy):
    pass
