# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.salaries_update_salary_response_data import SalariesUpdateSalaryResponseData
from sesame_hr_python_sdk.type.salaries_update_salary_response_meta import SalariesUpdateSalaryResponseMeta

class RequiredSalariesUpdateSalaryResponse(TypedDict):
    pass

class OptionalSalariesUpdateSalaryResponse(TypedDict, total=False):
    data: SalariesUpdateSalaryResponseData

    meta: SalariesUpdateSalaryResponseMeta

class SalariesUpdateSalaryResponse(RequiredSalariesUpdateSalaryResponse, OptionalSalariesUpdateSalaryResponse):
    pass
