# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSalariesCreateSalaryRequest(TypedDict):
    # The ID of the employee
    employeeId: str

    # Payment period of contract
    payPeriod: str

    # Currency of contract
    currency: str

    # Salary amount
    grossSalary: typing.Union[int, float]

    # Number of payments
    payments: int

    # Contribution group id
    contributionGroupId: str

    # Salary start date
    startDate: date

class OptionalSalariesCreateSalaryRequest(TypedDict, total=False):
    # Salary end date
    endDate: date

    # Comments
    comments: str

class SalariesCreateSalaryRequest(RequiredSalariesCreateSalaryRequest, OptionalSalariesCreateSalaryRequest):
    pass
