# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.schedule_templates_list_response_data import ScheduleTemplatesListResponseData
from sesame_hr_python_sdk.type.schedule_templates_list_response_meta import ScheduleTemplatesListResponseMeta

class RequiredScheduleTemplatesListResponse(TypedDict):
    pass

class OptionalScheduleTemplatesListResponse(TypedDict, total=False):
    data: ScheduleTemplatesListResponseData

    meta: ScheduleTemplatesListResponseMeta

class ScheduleTemplatesListResponse(RequiredScheduleTemplatesListResponse, OptionalScheduleTemplatesListResponse):
    pass
