# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.statistics_list_worked_absence_days_by_employee_response_data import StatisticsListWorkedAbsenceDaysByEmployeeResponseData
from sesame_hr_python_sdk.type.statistics_list_worked_absence_days_by_employee_response_meta import StatisticsListWorkedAbsenceDaysByEmployeeResponseMeta

class RequiredStatisticsListWorkedAbsenceDaysByEmployeeResponse(TypedDict):
    pass

class OptionalStatisticsListWorkedAbsenceDaysByEmployeeResponse(TypedDict, total=False):
    data: StatisticsListWorkedAbsenceDaysByEmployeeResponseData

    meta: StatisticsListWorkedAbsenceDaysByEmployeeResponseMeta

class StatisticsListWorkedAbsenceDaysByEmployeeResponse(RequiredStatisticsListWorkedAbsenceDaysByEmployeeResponse, OptionalStatisticsListWorkedAbsenceDaysByEmployeeResponse):
    pass
