# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.time_entries_create_new_entry_response_data import TimeEntriesCreateNewEntryResponseData
from sesame_hr_python_sdk.type.time_entries_create_new_entry_response_meta import TimeEntriesCreateNewEntryResponseMeta

class RequiredTimeEntriesCreateNewEntryResponse(TypedDict):
    pass

class OptionalTimeEntriesCreateNewEntryResponse(TypedDict, total=False):
    data: TimeEntriesCreateNewEntryResponseData

    meta: TimeEntriesCreateNewEntryResponseMeta

class TimeEntriesCreateNewEntryResponse(RequiredTimeEntriesCreateNewEntryResponse, OptionalTimeEntriesCreateNewEntryResponse):
    pass
