# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.vacation_day_off_requests_list_response_data_item_vacation_calendar_days_off import VacationDayOffRequestsListResponseDataItemVacationCalendarDaysOff
from sesame_hr_python_sdk.type.vacation_day_off_requests_list_response_data_item_vacation_calendar_employee import VacationDayOffRequestsListResponseDataItemVacationCalendarEmployee
from sesame_hr_python_sdk.type.vacation_day_off_requests_list_response_data_item_vacation_calendar_vacation_configuration import VacationDayOffRequestsListResponseDataItemVacationCalendarVacationConfiguration

class RequiredVacationDayOffRequestsListResponseDataItemVacationCalendar(TypedDict):
    pass

class OptionalVacationDayOffRequestsListResponseDataItemVacationCalendar(TypedDict, total=False):
    id: str

    employee: VacationDayOffRequestsListResponseDataItemVacationCalendarEmployee

    daysOff: VacationDayOffRequestsListResponseDataItemVacationCalendarDaysOff

    maxDaysOff: int

    year: int

    vacationConfiguration: VacationDayOffRequestsListResponseDataItemVacationCalendarVacationConfiguration

    createdAt: str

    updatedAt: str

    deletedAt: str

class VacationDayOffRequestsListResponseDataItemVacationCalendar(RequiredVacationDayOffRequestsListResponseDataItemVacationCalendar, OptionalVacationDayOffRequestsListResponseDataItemVacationCalendar):
    pass
