# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.vacation_calendars_update_calendar_response_data_days_off import VacationCalendarsUpdateCalendarResponseDataDaysOff
from sesame_hr_python_sdk.type.vacation_calendars_update_calendar_response_data_employee import VacationCalendarsUpdateCalendarResponseDataEmployee
from sesame_hr_python_sdk.type.vacation_calendars_update_calendar_response_data_vacation_configuration import VacationCalendarsUpdateCalendarResponseDataVacationConfiguration

class RequiredVacationCalendarsUpdateCalendarResponseData(TypedDict):
    pass

class OptionalVacationCalendarsUpdateCalendarResponseData(TypedDict, total=False):
    id: str

    employee: VacationCalendarsUpdateCalendarResponseDataEmployee

    daysOff: VacationCalendarsUpdateCalendarResponseDataDaysOff

    maxDaysOff: int

    year: int

    vacationConfiguration: VacationCalendarsUpdateCalendarResponseDataVacationConfiguration

    createdAt: str

    updatedAt: str

    deletedAt: str

class VacationCalendarsUpdateCalendarResponseData(RequiredVacationCalendarsUpdateCalendarResponseData, OptionalVacationCalendarsUpdateCalendarResponseData):
    pass
