# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.vacation_day_off_list_response_data_item_calendar_vacation_configuration_not_allowed_date_ranges import VacationDayOffListResponseDataItemCalendarVacationConfigurationNotAllowedDateRanges

class RequiredVacationDayOffListResponseDataItemCalendarVacationConfiguration(TypedDict):
    pass

class OptionalVacationDayOffListResponseDataItemCalendarVacationConfiguration(TypedDict, total=False):
    id: str

    name: str

    employeeRequestEnabled: bool

    needsValidation: bool

    dayType: str

    maxDaysOff: int

    isDefault: bool

    notAllowedDateRanges: VacationDayOffListResponseDataItemCalendarVacationConfigurationNotAllowedDateRanges

    createdAt: str

    updatedAt: str

    createdBy: str

class VacationDayOffListResponseDataItemCalendarVacationConfiguration(RequiredVacationDayOffListResponseDataItemCalendarVacationConfiguration, OptionalVacationDayOffListResponseDataItemCalendarVacationConfiguration):
    pass
