# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sesame_hr_python_sdk.type.work_entries_list_response_data_item_employee import WorkEntriesListResponseDataItemEmployee
from sesame_hr_python_sdk.type.work_entries_list_response_data_item_work_entry_in import WorkEntriesListResponseDataItemWorkEntryIn
from sesame_hr_python_sdk.type.work_entries_list_response_data_item_work_entry_out import WorkEntriesListResponseDataItemWorkEntryOut

class RequiredWorkEntriesListResponseDataItem(TypedDict):
    pass

class OptionalWorkEntriesListResponseDataItem(TypedDict, total=False):
    id: str

    workCheckTypeId: str

    employee: WorkEntriesListResponseDataItemEmployee

    workEntryType: str

    workEntryIn: WorkEntriesListResponseDataItemWorkEntryIn

    workEntryOut: WorkEntriesListResponseDataItemWorkEntryOut

    workedSeconds: typing.Union[int, float]

    createdAt: str

    updatedAt: str

    deletedAt: str

class WorkEntriesListResponseDataItem(RequiredWorkEntriesListResponseDataItem, OptionalWorkEntriesListResponseDataItem):
    pass
