# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from sesame_hr_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from sesame_hr_python_sdk.api_response import AsyncGeneratorResponse
from sesame_hr_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sesame_hr_python_sdk import schemas  # noqa: F401

from sesame_hr_python_sdk.model.absence_day_off_requests_list_day_off_requests_response import AbsenceDayOffRequestsListDayOffRequestsResponse as AbsenceDayOffRequestsListDayOffRequestsResponseSchema

from sesame_hr_python_sdk.type.absence_day_off_requests_list_day_off_requests_response import AbsenceDayOffRequestsListDayOffRequestsResponse

from ...api_client import Dictionary
from sesame_hr_python_sdk.pydantic.absence_day_off_requests_list_day_off_requests_response import AbsenceDayOffRequestsListDayOffRequestsResponse as AbsenceDayOffRequestsListDayOffRequestsResponsePydantic

# Query params
EmployeeIdSchema = schemas.UUIDSchema
AbsencesValidatorSchema = schemas.UUIDSchema
FromDayOffSchema = schemas.DateSchema
ToDayOffSchema = schemas.DateSchema


class StatusSchema(
    schemas.EnumBase,
    schemas.StrSchema
):
    
    @schemas.classproperty
    def ACCEPTED(cls):
        return cls("accepted")
    
    @schemas.classproperty
    def REJECTED(cls):
        return cls("rejected")
    
    @schemas.classproperty
    def PENDING(cls):
        return cls("pending")
LimitSchema = schemas.IntSchema
PageSchema = schemas.IntSchema
OrderBySchema = schemas.StrSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'employeeId': typing.Union[EmployeeIdSchema, str, uuid.UUID, ],
        'absencesValidator': typing.Union[AbsencesValidatorSchema, str, uuid.UUID, ],
        'fromDayOff': typing.Union[FromDayOffSchema, str, date, ],
        'toDayOff': typing.Union[ToDayOffSchema, str, date, ],
        'status': typing.Union[StatusSchema, str, ],
        'limit': typing.Union[LimitSchema, decimal.Decimal, int, ],
        'page': typing.Union[PageSchema, decimal.Decimal, int, ],
        'orderBy': typing.Union[OrderBySchema, str, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_employee_id = api_client.QueryParameter(
    name="employeeId",
    style=api_client.ParameterStyle.FORM,
    schema=EmployeeIdSchema,
    explode=True,
)
request_query_absences_validator = api_client.QueryParameter(
    name="absencesValidator",
    style=api_client.ParameterStyle.FORM,
    schema=AbsencesValidatorSchema,
    explode=True,
)
request_query_from_day_off = api_client.QueryParameter(
    name="fromDayOff",
    style=api_client.ParameterStyle.FORM,
    schema=FromDayOffSchema,
    explode=True,
)
request_query_to_day_off = api_client.QueryParameter(
    name="toDayOff",
    style=api_client.ParameterStyle.FORM,
    schema=ToDayOffSchema,
    explode=True,
)
request_query_status = api_client.QueryParameter(
    name="status",
    style=api_client.ParameterStyle.FORM,
    schema=StatusSchema,
    explode=True,
)
request_query_limit = api_client.QueryParameter(
    name="limit",
    style=api_client.ParameterStyle.FORM,
    schema=LimitSchema,
    explode=True,
)
request_query_page = api_client.QueryParameter(
    name="page",
    style=api_client.ParameterStyle.FORM,
    schema=PageSchema,
    explode=True,
)
request_query_order_by = api_client.QueryParameter(
    name="orderBy",
    style=api_client.ParameterStyle.FORM,
    schema=OrderBySchema,
    explode=True,
)
SchemaFor200ResponseBodyApplicationJson = AbsenceDayOffRequestsListDayOffRequestsResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: AbsenceDayOffRequestsListDayOffRequestsResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: AbsenceDayOffRequestsListDayOffRequestsResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _list_day_off_requests_mapped_args(
        self,
        employee_id: typing.Optional[str] = None,
        absences_validator: typing.Optional[str] = None,
        from_day_off: typing.Optional[date] = None,
        to_day_off: typing.Optional[date] = None,
        status: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        if employee_id is not None:
            _query_params["employeeId"] = employee_id
        if absences_validator is not None:
            _query_params["absencesValidator"] = absences_validator
        if from_day_off is not None:
            _query_params["fromDayOff"] = from_day_off
        if to_day_off is not None:
            _query_params["toDayOff"] = to_day_off
        if status is not None:
            _query_params["status"] = status
        if limit is not None:
            _query_params["limit"] = limit
        if page is not None:
            _query_params["page"] = page
        if order_by is not None:
            _query_params["orderBy"] = order_by
        args.query = _query_params
        return args

    async def _alist_day_off_requests_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        List Absence Day Off Requests
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_employee_id,
            request_query_absences_validator,
            request_query_from_day_off,
            request_query_to_day_off,
            request_query_status,
            request_query_limit,
            request_query_page,
            request_query_order_by,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/schedule/v1/absence-day-off-requests',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _list_day_off_requests_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        List Absence Day Off Requests
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_employee_id,
            request_query_absences_validator,
            request_query_from_day_off,
            request_query_to_day_off,
            request_query_status,
            request_query_limit,
            request_query_page,
            request_query_order_by,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/schedule/v1/absence-day-off-requests',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class ListDayOffRequestsRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def alist_day_off_requests(
        self,
        employee_id: typing.Optional[str] = None,
        absences_validator: typing.Optional[str] = None,
        from_day_off: typing.Optional[date] = None,
        to_day_off: typing.Optional[date] = None,
        status: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._list_day_off_requests_mapped_args(
            employee_id=employee_id,
            absences_validator=absences_validator,
            from_day_off=from_day_off,
            to_day_off=to_day_off,
            status=status,
            limit=limit,
            page=page,
            order_by=order_by,
        )
        return await self._alist_day_off_requests_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def list_day_off_requests(
        self,
        employee_id: typing.Optional[str] = None,
        absences_validator: typing.Optional[str] = None,
        from_day_off: typing.Optional[date] = None,
        to_day_off: typing.Optional[date] = None,
        status: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._list_day_off_requests_mapped_args(
            employee_id=employee_id,
            absences_validator=absences_validator,
            from_day_off=from_day_off,
            to_day_off=to_day_off,
            status=status,
            limit=limit,
            page=page,
            order_by=order_by,
        )
        return self._list_day_off_requests_oapg(
            query_params=args.query,
        )

class ListDayOffRequests(BaseApi):

    async def alist_day_off_requests(
        self,
        employee_id: typing.Optional[str] = None,
        absences_validator: typing.Optional[str] = None,
        from_day_off: typing.Optional[date] = None,
        to_day_off: typing.Optional[date] = None,
        status: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        validate: bool = False,
        **kwargs,
    ) -> AbsenceDayOffRequestsListDayOffRequestsResponsePydantic:
        raw_response = await self.raw.alist_day_off_requests(
            employee_id=employee_id,
            absences_validator=absences_validator,
            from_day_off=from_day_off,
            to_day_off=to_day_off,
            status=status,
            limit=limit,
            page=page,
            order_by=order_by,
            **kwargs,
        )
        if validate:
            return AbsenceDayOffRequestsListDayOffRequestsResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(AbsenceDayOffRequestsListDayOffRequestsResponsePydantic, raw_response.body)
    
    
    def list_day_off_requests(
        self,
        employee_id: typing.Optional[str] = None,
        absences_validator: typing.Optional[str] = None,
        from_day_off: typing.Optional[date] = None,
        to_day_off: typing.Optional[date] = None,
        status: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        validate: bool = False,
    ) -> AbsenceDayOffRequestsListDayOffRequestsResponsePydantic:
        raw_response = self.raw.list_day_off_requests(
            employee_id=employee_id,
            absences_validator=absences_validator,
            from_day_off=from_day_off,
            to_day_off=to_day_off,
            status=status,
            limit=limit,
            page=page,
            order_by=order_by,
        )
        if validate:
            return AbsenceDayOffRequestsListDayOffRequestsResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(AbsenceDayOffRequestsListDayOffRequestsResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        employee_id: typing.Optional[str] = None,
        absences_validator: typing.Optional[str] = None,
        from_day_off: typing.Optional[date] = None,
        to_day_off: typing.Optional[date] = None,
        status: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._list_day_off_requests_mapped_args(
            employee_id=employee_id,
            absences_validator=absences_validator,
            from_day_off=from_day_off,
            to_day_off=to_day_off,
            status=status,
            limit=limit,
            page=page,
            order_by=order_by,
        )
        return await self._alist_day_off_requests_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get(
        self,
        employee_id: typing.Optional[str] = None,
        absences_validator: typing.Optional[str] = None,
        from_day_off: typing.Optional[date] = None,
        to_day_off: typing.Optional[date] = None,
        status: typing.Optional[str] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        order_by: typing.Optional[str] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._list_day_off_requests_mapped_args(
            employee_id=employee_id,
            absences_validator=absences_validator,
            from_day_off=from_day_off,
            to_day_off=to_day_off,
            status=status,
            limit=limit,
            page=page,
            order_by=order_by,
        )
        return self._list_day_off_requests_oapg(
            query_params=args.query,
        )

