# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sesame_hr_python_sdk import schemas  # noqa: F401


class HolidaysListResponseDataItem(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def employee() -> typing.Type['HolidaysListResponseDataItemEmployee']:
                return HolidaysListResponseDataItemEmployee
        
            @staticmethod
            def dayOff() -> typing.Type['HolidaysListResponseDataItemDayOff']:
                return HolidaysListResponseDataItemDayOff
            __annotations__ = {
                "employee": employee,
                "dayOff": dayOff,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employee"]) -> 'HolidaysListResponseDataItemEmployee': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["dayOff"]) -> 'HolidaysListResponseDataItemDayOff': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["employee", "dayOff", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employee"]) -> typing.Union['HolidaysListResponseDataItemEmployee', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["dayOff"]) -> typing.Union['HolidaysListResponseDataItemDayOff', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["employee", "dayOff", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        employee: typing.Union['HolidaysListResponseDataItemEmployee', schemas.Unset] = schemas.unset,
        dayOff: typing.Union['HolidaysListResponseDataItemDayOff', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'HolidaysListResponseDataItem':
        return super().__new__(
            cls,
            *args,
            employee=employee,
            dayOff=dayOff,
            _configuration=_configuration,
            **kwargs,
        )

from sesame_hr_python_sdk.model.holidays_list_response_data_item_day_off import HolidaysListResponseDataItemDayOff
from sesame_hr_python_sdk.model.holidays_list_response_data_item_employee import HolidaysListResponseDataItemEmployee
