# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sesame_hr_python_sdk import schemas  # noqa: F401


class TimeEntriesStartEntryResponseData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            id = schemas.UUIDSchema
        
            @staticmethod
            def employee() -> typing.Type['TimeEntriesStartEntryResponseDataEmployee']:
                return TimeEntriesStartEntryResponseDataEmployee
            projectId = schemas.UUIDSchema
        
            @staticmethod
            def tagIds() -> typing.Type['TimeEntriesStartEntryResponseDataTagIds']:
                return TimeEntriesStartEntryResponseDataTagIds
        
            @staticmethod
            def timeEntryIn() -> typing.Type['TimeEntriesStartEntryResponseDataTimeEntryIn']:
                return TimeEntriesStartEntryResponseDataTimeEntryIn
            timeEntryOut = schemas.DictSchema
            comment = schemas.StrSchema
            createdAt = schemas.StrSchema
            updatedAt = schemas.StrSchema
            
            
            class deletedAt(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                def __new__(
                    cls,
                    *args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'deletedAt':
                    return super().__new__(
                        cls,
                        *args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "id": id,
                "employee": employee,
                "projectId": projectId,
                "tagIds": tagIds,
                "timeEntryIn": timeEntryIn,
                "timeEntryOut": timeEntryOut,
                "comment": comment,
                "createdAt": createdAt,
                "updatedAt": updatedAt,
                "deletedAt": deletedAt,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["employee"]) -> 'TimeEntriesStartEntryResponseDataEmployee': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["projectId"]) -> MetaOapg.properties.projectId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tagIds"]) -> 'TimeEntriesStartEntryResponseDataTagIds': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timeEntryIn"]) -> 'TimeEntriesStartEntryResponseDataTimeEntryIn': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["timeEntryOut"]) -> MetaOapg.properties.timeEntryOut: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["comment"]) -> MetaOapg.properties.comment: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["createdAt"]) -> MetaOapg.properties.createdAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["updatedAt"]) -> MetaOapg.properties.updatedAt: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["deletedAt"]) -> MetaOapg.properties.deletedAt: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["id", "employee", "projectId", "tagIds", "timeEntryIn", "timeEntryOut", "comment", "createdAt", "updatedAt", "deletedAt", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> typing.Union[MetaOapg.properties.id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["employee"]) -> typing.Union['TimeEntriesStartEntryResponseDataEmployee', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["projectId"]) -> typing.Union[MetaOapg.properties.projectId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tagIds"]) -> typing.Union['TimeEntriesStartEntryResponseDataTagIds', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timeEntryIn"]) -> typing.Union['TimeEntriesStartEntryResponseDataTimeEntryIn', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["timeEntryOut"]) -> typing.Union[MetaOapg.properties.timeEntryOut, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["comment"]) -> typing.Union[MetaOapg.properties.comment, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["createdAt"]) -> typing.Union[MetaOapg.properties.createdAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["updatedAt"]) -> typing.Union[MetaOapg.properties.updatedAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["deletedAt"]) -> typing.Union[MetaOapg.properties.deletedAt, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["id", "employee", "projectId", "tagIds", "timeEntryIn", "timeEntryOut", "comment", "createdAt", "updatedAt", "deletedAt", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        id: typing.Union[MetaOapg.properties.id, str, uuid.UUID, schemas.Unset] = schemas.unset,
        employee: typing.Union['TimeEntriesStartEntryResponseDataEmployee', schemas.Unset] = schemas.unset,
        projectId: typing.Union[MetaOapg.properties.projectId, str, uuid.UUID, schemas.Unset] = schemas.unset,
        tagIds: typing.Union['TimeEntriesStartEntryResponseDataTagIds', schemas.Unset] = schemas.unset,
        timeEntryIn: typing.Union['TimeEntriesStartEntryResponseDataTimeEntryIn', schemas.Unset] = schemas.unset,
        timeEntryOut: typing.Union[MetaOapg.properties.timeEntryOut, dict, frozendict.frozendict, schemas.Unset] = schemas.unset,
        comment: typing.Union[MetaOapg.properties.comment, str, schemas.Unset] = schemas.unset,
        createdAt: typing.Union[MetaOapg.properties.createdAt, str, schemas.Unset] = schemas.unset,
        updatedAt: typing.Union[MetaOapg.properties.updatedAt, str, schemas.Unset] = schemas.unset,
        deletedAt: typing.Union[MetaOapg.properties.deletedAt, None, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'TimeEntriesStartEntryResponseData':
        return super().__new__(
            cls,
            *args,
            id=id,
            employee=employee,
            projectId=projectId,
            tagIds=tagIds,
            timeEntryIn=timeEntryIn,
            timeEntryOut=timeEntryOut,
            comment=comment,
            createdAt=createdAt,
            updatedAt=updatedAt,
            deletedAt=deletedAt,
            _configuration=_configuration,
            **kwargs,
        )

from sesame_hr_python_sdk.model.time_entries_start_entry_response_data_employee import TimeEntriesStartEntryResponseDataEmployee
from sesame_hr_python_sdk.model.time_entries_start_entry_response_data_tag_ids import TimeEntriesStartEntryResponseDataTagIds
from sesame_hr_python_sdk.model.time_entries_start_entry_response_data_time_entry_in import TimeEntriesStartEntryResponseDataTimeEntryIn
