# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from sesame_hr_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from sesame_hr_python_sdk.api_response import AsyncGeneratorResponse
from sesame_hr_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sesame_hr_python_sdk import schemas  # noqa: F401

from sesame_hr_python_sdk.model.statistics_list_worked_hours_by_employee_response import StatisticsListWorkedHoursByEmployeeResponse as StatisticsListWorkedHoursByEmployeeResponseSchema

from sesame_hr_python_sdk.type.statistics_list_worked_hours_by_employee_response import StatisticsListWorkedHoursByEmployeeResponse

from ...api_client import Dictionary
from sesame_hr_python_sdk.pydantic.statistics_list_worked_hours_by_employee_response import StatisticsListWorkedHoursByEmployeeResponse as StatisticsListWorkedHoursByEmployeeResponsePydantic

from . import path

# Query params


class EmployeeIdsInSchema(
    schemas.ListSchema
):


    class MetaOapg:
        items = schemas.UUIDSchema

    def __new__(
        cls,
        arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, uuid.UUID, ]], typing.List[typing.Union[MetaOapg.items, str, uuid.UUID, ]]],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'EmployeeIdsInSchema':
        return super().__new__(
            cls,
            arg,
            _configuration=_configuration,
        )

    def __getitem__(self, i: int) -> MetaOapg.items:
        return super().__getitem__(i)
WithChecksSchema = schemas.BoolSchema
ModelFromSchema = schemas.DateSchema
ToSchema = schemas.DateSchema
LimitSchema = schemas.IntSchema
PageSchema = schemas.IntSchema
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
        'from': typing.Union[ModelFromSchema, str, date, ],
        'to': typing.Union[ToSchema, str, date, ],
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'employeeIds[in]': typing.Union[EmployeeIdsInSchema, list, tuple, ],
        'withChecks': typing.Union[WithChecksSchema, bool, ],
        'limit': typing.Union[LimitSchema, decimal.Decimal, int, ],
        'page': typing.Union[PageSchema, decimal.Decimal, int, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_employee_ids_in = api_client.QueryParameter(
    name="employeeIds[in]",
    style=api_client.ParameterStyle.FORM,
    schema=EmployeeIdsInSchema,
)
request_query_with_checks = api_client.QueryParameter(
    name="withChecks",
    style=api_client.ParameterStyle.FORM,
    schema=WithChecksSchema,
    explode=True,
)
request_query__from = api_client.QueryParameter(
    name="from",
    style=api_client.ParameterStyle.FORM,
    schema=ModelFromSchema,
    required=True,
    explode=True,
)
request_query_to = api_client.QueryParameter(
    name="to",
    style=api_client.ParameterStyle.FORM,
    schema=ToSchema,
    required=True,
    explode=True,
)
request_query_limit = api_client.QueryParameter(
    name="limit",
    style=api_client.ParameterStyle.FORM,
    schema=LimitSchema,
    explode=True,
)
request_query_page = api_client.QueryParameter(
    name="page",
    style=api_client.ParameterStyle.FORM,
    schema=PageSchema,
    explode=True,
)
_auth = [
    'Bearer',
]
SchemaFor200ResponseBodyApplicationJson = StatisticsListWorkedHoursByEmployeeResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: StatisticsListWorkedHoursByEmployeeResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: StatisticsListWorkedHoursByEmployeeResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _list_worked_hours_by_employee_mapped_args(
        self,
        _from: date,
        to: date,
        employee_ids_in: typing.Optional[typing.List[str]] = None,
        with_checks: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        if employee_ids_in is not None:
            _query_params["employeeIds[in]"] = employee_ids_in
        if with_checks is not None:
            _query_params["withChecks"] = with_checks
        if _from is not None:
            _query_params["from"] = _from
        if to is not None:
            _query_params["to"] = to
        if limit is not None:
            _query_params["limit"] = limit
        if page is not None:
            _query_params["page"] = page
        args.query = _query_params
        return args

    async def _alist_worked_hours_by_employee_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        List Worked Hours By Employee
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_employee_ids_in,
            request_query_with_checks,
            request_query__from,
            request_query_to,
            request_query_limit,
            request_query_page,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/schedule/v1/reports/worked-hours',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _list_worked_hours_by_employee_oapg(
        self,
            query_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        List Worked Hours By Employee
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        used_path = path.value
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_employee_ids_in,
            request_query_with_checks,
            request_query__from,
            request_query_to,
            request_query_limit,
            request_query_page,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/schedule/v1/reports/worked-hours',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class ListWorkedHoursByEmployeeRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def alist_worked_hours_by_employee(
        self,
        _from: date,
        to: date,
        employee_ids_in: typing.Optional[typing.List[str]] = None,
        with_checks: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._list_worked_hours_by_employee_mapped_args(
            _from=_from,
            to=to,
            employee_ids_in=employee_ids_in,
            with_checks=with_checks,
            limit=limit,
            page=page,
        )
        return await self._alist_worked_hours_by_employee_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def list_worked_hours_by_employee(
        self,
        _from: date,
        to: date,
        employee_ids_in: typing.Optional[typing.List[str]] = None,
        with_checks: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._list_worked_hours_by_employee_mapped_args(
            _from=_from,
            to=to,
            employee_ids_in=employee_ids_in,
            with_checks=with_checks,
            limit=limit,
            page=page,
        )
        return self._list_worked_hours_by_employee_oapg(
            query_params=args.query,
        )

class ListWorkedHoursByEmployee(BaseApi):

    async def alist_worked_hours_by_employee(
        self,
        _from: date,
        to: date,
        employee_ids_in: typing.Optional[typing.List[str]] = None,
        with_checks: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        validate: bool = False,
        **kwargs,
    ) -> StatisticsListWorkedHoursByEmployeeResponsePydantic:
        raw_response = await self.raw.alist_worked_hours_by_employee(
            _from=_from,
            to=to,
            employee_ids_in=employee_ids_in,
            with_checks=with_checks,
            limit=limit,
            page=page,
            **kwargs,
        )
        if validate:
            return StatisticsListWorkedHoursByEmployeeResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(StatisticsListWorkedHoursByEmployeeResponsePydantic, raw_response.body)
    
    
    def list_worked_hours_by_employee(
        self,
        _from: date,
        to: date,
        employee_ids_in: typing.Optional[typing.List[str]] = None,
        with_checks: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        validate: bool = False,
    ) -> StatisticsListWorkedHoursByEmployeeResponsePydantic:
        raw_response = self.raw.list_worked_hours_by_employee(
            _from=_from,
            to=to,
            employee_ids_in=employee_ids_in,
            with_checks=with_checks,
            limit=limit,
            page=page,
        )
        if validate:
            return StatisticsListWorkedHoursByEmployeeResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(StatisticsListWorkedHoursByEmployeeResponsePydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        _from: date,
        to: date,
        employee_ids_in: typing.Optional[typing.List[str]] = None,
        with_checks: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._list_worked_hours_by_employee_mapped_args(
            _from=_from,
            to=to,
            employee_ids_in=employee_ids_in,
            with_checks=with_checks,
            limit=limit,
            page=page,
        )
        return await self._alist_worked_hours_by_employee_oapg(
            query_params=args.query,
            **kwargs,
        )
    
    def get(
        self,
        _from: date,
        to: date,
        employee_ids_in: typing.Optional[typing.List[str]] = None,
        with_checks: typing.Optional[bool] = None,
        limit: typing.Optional[int] = None,
        page: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._list_worked_hours_by_employee_mapped_args(
            _from=_from,
            to=to,
            employee_ids_in=employee_ids_in,
            with_checks=with_checks,
            limit=limit,
            page=page,
        )
        return self._list_worked_hours_by_employee_oapg(
            query_params=args.query,
        )

