# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from sesame_hr_python_sdk.paths.schedule_v1_agreements.post import CreateNewAgreementRaw
from sesame_hr_python_sdk.paths.schedule_v1_agreements_agreement_id.delete import DeleteAgreementRaw
from sesame_hr_python_sdk.paths.schedule_v1_agreements_agreement_id.get import GetAgreementRaw
from sesame_hr_python_sdk.paths.schedule_v1_agreements.get import ListRaw
from sesame_hr_python_sdk.paths.schedule_v1_agreements_agreement_id.put import UpdateAgreementRaw


class AgreementsApiRaw(
    CreateNewAgreementRaw,
    DeleteAgreementRaw,
    GetAgreementRaw,
    ListRaw,
    UpdateAgreementRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
