# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from sesame_hr_python_sdk.paths.contract_v1_contracts.post import CreateNewContractRaw
from sesame_hr_python_sdk.paths.contract_v1_contracts_contract_id.delete import DeleteContractRaw
from sesame_hr_python_sdk.paths.contract_v1_contracts_employee_id.get import GetByEmployeeIdRaw
from sesame_hr_python_sdk.paths.contract_v1_contracts_employee_id_current_contract.get import GetCurrentContractByEmployeeIdRaw
from sesame_hr_python_sdk.paths.contract_v1_contracts_contract_id.put import UpdateContractRaw


class ContractsApiRaw(
    CreateNewContractRaw,
    DeleteContractRaw,
    GetByEmployeeIdRaw,
    GetCurrentContractByEmployeeIdRaw,
    UpdateContractRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
