# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from sesame_hr_python_sdk.paths.project_v1_customers.post import CreateNewCustomerRaw
from sesame_hr_python_sdk.paths.project_v1_customers.get import ListRaw
from sesame_hr_python_sdk.paths.project_v1_customers_id.delete import RemoveByIdRaw
from sesame_hr_python_sdk.paths.project_v1_customers_id.put import UpdateCustomerRaw


class CustomersApiRaw(
    CreateNewCustomerRaw,
    ListRaw,
    RemoveByIdRaw,
    UpdateCustomerRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
