# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from sesame_hr_python_sdk.paths.project_v1_customers.post import CreateNewCustomer
from sesame_hr_python_sdk.paths.project_v1_customers.get import List
from sesame_hr_python_sdk.paths.project_v1_customers_id.delete import RemoveById
from sesame_hr_python_sdk.paths.project_v1_customers_id.put import UpdateCustomer
from sesame_hr_python_sdk.apis.tags.customers_api_raw import CustomersApiRaw


class CustomersApi(
    CreateNewCustomer,
    List,
    RemoveById,
    UpdateCustomer,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: CustomersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = CustomersApiRaw(api_client)
