# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from sesame_hr_python_sdk.paths.core_v3_departments.post import CreateNewDepartmentRaw
from sesame_hr_python_sdk.paths.core_v3_departments.get import ListRaw
from sesame_hr_python_sdk.paths.core_v3_departments_id.delete import RemoveByIdRaw
from sesame_hr_python_sdk.paths.core_v3_departments_id.put import UpdateByIdRaw


class DepartmentsApiRaw(
    CreateNewDepartmentRaw,
    ListRaw,
    RemoveByIdRaw,
    UpdateByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
