# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from sesame_hr_python_sdk.paths.core_v3_employees.post import CreateNewEmployee
from sesame_hr_python_sdk.paths.core_v3_employees_id.get import GetById
from sesame_hr_python_sdk.paths.core_v3_employees.get import List
from sesame_hr_python_sdk.paths.core_v3_employees_id.delete import RemoveById
from sesame_hr_python_sdk.paths.core_v3_employees_id.put import UpdateById
from sesame_hr_python_sdk.apis.tags.employees_api_raw import EmployeesApiRaw


class EmployeesApi(
    CreateNewEmployee,
    GetById,
    List,
    RemoveById,
    UpdateById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EmployeesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EmployeesApiRaw(api_client)
