# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from sesame_hr_python_sdk.paths.schedule_v1_agreement_employees.post import AssignEmployee
from sesame_hr_python_sdk.paths.schedule_v1_agreement_employees_agreement_employee_id.delete import UnassignEmployee
from sesame_hr_python_sdk.apis.tags.employee_agreements_api_raw import EmployeeAgreementsApiRaw


class EmployeeAgreementsApi(
    AssignEmployee,
    UnassignEmployee,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EmployeeAgreementsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EmployeeAgreementsApiRaw(api_client)
