# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from sesame_hr_python_sdk.paths.schedule_v1_entity_schedule_templates.post import CreateEmployeeScheduleTemplate
from sesame_hr_python_sdk.paths.schedule_v1_employees_employee_id_schedule_templates.get import ListTemplates
from sesame_hr_python_sdk.paths.schedule_v1_entity_schedule_templates_entity_schedule_template_id.delete import Unassign
from sesame_hr_python_sdk.apis.tags.employee_schedule_templates_api_raw import EmployeeScheduleTemplatesApiRaw


class EmployeeScheduleTemplatesApi(
    CreateEmployeeScheduleTemplate,
    ListTemplates,
    Unassign,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EmployeeScheduleTemplatesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EmployeeScheduleTemplatesApiRaw(api_client)
