# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from sesame_hr_python_sdk.paths.core_v3_roles_assignation.post import AssignRoleRaw
from sesame_hr_python_sdk.paths.core_v3_roles_assignation_employee_id.get import ListByEmployeeRaw
from sesame_hr_python_sdk.paths.core_v3_roles_assignation.delete import UnassignRoleRaw


class EmployeeAssignationsRolesApiRaw(
    AssignRoleRaw,
    ListByEmployeeRaw,
    UnassignRoleRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
