# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from sesame_hr_python_sdk.paths.project_v1_projects.post import CreateProject
from sesame_hr_python_sdk.paths.project_v1_projects.get import List
from sesame_hr_python_sdk.paths.project_v1_projects_id.delete import RemoveById
from sesame_hr_python_sdk.paths.project_v1_projects_id.put import UpdateProjectById
from sesame_hr_python_sdk.apis.tags.projects_api_raw import ProjectsApiRaw


class ProjectsApi(
    CreateProject,
    List,
    RemoveById,
    UpdateProjectById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: ProjectsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = ProjectsApiRaw(api_client)
