# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from sesame_hr_python_sdk.paths.contract_v1_salaries.post import CreateSalary
from sesame_hr_python_sdk.paths.contract_v1_salaries_salary_id.delete import DeleteSalary
from sesame_hr_python_sdk.paths.contract_v1_salaries.get import List
from sesame_hr_python_sdk.paths.contract_v1_contribution_groups.get import ListContributionGroups
from sesame_hr_python_sdk.paths.contract_v1_salaries_salary_id.put import UpdateSalary
from sesame_hr_python_sdk.apis.tags.salaries_api_raw import SalariesApiRaw


class SalariesApi(
    CreateSalary,
    DeleteSalary,
    List,
    ListContributionGroups,
    UpdateSalary,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SalariesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SalariesApiRaw(api_client)
