# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from sesame_hr_python_sdk.paths.schedule_v1_vacation_calendars.post import CreateNewCalendar
from sesame_hr_python_sdk.paths.schedule_v1_vacation_calendars.get import ListCalendars
from sesame_hr_python_sdk.paths.schedule_v1_vacation_calendars_id.put import UpdateCalendar
from sesame_hr_python_sdk.apis.tags.vacation_calendars_api_raw import VacationCalendarsApiRaw


class VacationCalendarsApi(
    CreateNewCalendar,
    ListCalendars,
    UpdateCalendar,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: VacationCalendarsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = VacationCalendarsApiRaw(api_client)
