# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

from sesame_hr_python_sdk.paths.schedule_v1_work_breaks.get import List
from sesame_hr_python_sdk.apis.tags.work_breaks_api_raw import WorkBreaksApiRaw


class WorkBreaksApi(
    List,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: WorkBreaksApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = WorkBreaksApiRaw(api_client)
