# coding: utf-8

"""
    Sesame Public API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 3.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import sesame_hr_python_sdk
from sesame_hr_python_sdk.paths.document_v1_directories_directory_id_documents import post
from sesame_hr_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestDocumentV1DirectoriesDirectoryIdDocuments(ApiTestMixin, unittest.TestCase):
    """
    DocumentV1DirectoriesDirectoryIdDocuments unit test stubs
        Upload document
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200






if __name__ == '__main__':
    unittest.main()
